// Export pages
export 'login/login_widget.dart' show LoginWidget;
export 'setting/setting_widget.dart' show SettingWidget;
export 'edit_profile/edit_profile_widget.dart' show EditProfileWidget;
export 'my_profile/my_profile_widget.dart' show MyProfileWidget;
export 'academic_c/academic_c_widget.dart' show AcademicCWidget;
export 'forgotpassword/forgotpassword_widget.dart' show ForgotpasswordWidget;
export 'home_page/home_page_widget.dart' show HomePageWidget;
export 'imp_mail/imp_mail_widget.dart' show ImpMailWidget;
export 'contact_us/contact_us_widget.dart' show ContactUsWidget;
export 'i_dcard/i_dcard_widget.dart' show IDcardWidget;
export 'aboutus/aboutus_widget.dart' show AboutusWidget;
export 'event/event_widget.dart' show EventWidget;
export 'study_material/study_material_widget.dart' show StudyMaterialWidget;
export 'semester1/semester1_widget.dart' show Semester1Widget;
export 'semeste2/semeste2_widget.dart' show Semeste2Widget;
export 'books/books_widget.dart' show BooksWidget;
export 'physics/physics_widget.dart' show PhysicsWidget;
export 'semestr3/semestr3_widget.dart' show Semestr3Widget;
